# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tml_po_number', models.BigIntegerField()),
                ('order_item_no', models.IntegerField()),
                ('field3', models.IntegerField()),
                ('field4', models.IntegerField()),
                ('field5', models.IntegerField()),
                ('field6', models.IntegerField()),
                ('field7', models.IntegerField()),
                ('field8', models.IntegerField()),
                ('field9', models.IntegerField()),
                ('field10', models.IntegerField()),
                ('field11', models.IntegerField()),
                ('field12', models.IntegerField()),
                ('field13', models.IntegerField()),
                ('field14', models.IntegerField()),
                ('field15', models.IntegerField()),
                ('field16', models.IntegerField()),
                ('field17', models.IntegerField()),
                ('field18', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='C:\\Users\\2200002708\\Documents\\')),
            ],
        ),
    ]
