# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('ward_no', models.PositiveIntegerField()),
                ('ward_name', models.CharField(max_length=200)),
                ('record_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
